# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33b0de826a70b43befe4409ebade9887867f2446ac8b2582d3ce499348cb10e5e739517cc0c7a993f7997e6855b83ccb4ad36496ea71d8b29a4cb9e0602572f8

test:
  secret_key_base: a82b926d5a2aa1048647ee9ac06cb12f45bfa7c4fcbc30c7d4a9b2dc639eaad8ec9b53e082d8f23944db37d983ff650667ecc59d9b20d79c198cf53366e50e40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
